In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [11]:
df_police_killings = pd.read_csv('deaths_arrests.csv')

In [12]:
df_police_killings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 46 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   State                                                          102 non-null    object
 1   City                                                           103 non-null    object
 2   PD                                                             102 non-null    object
 3   Black People Killed by Police (1/1/2013-12/31/2019)            93 non-null     float64
 4   Hispanic People Killed by Police (1/1/2013-12/31/2019)         71 non-null     float64
 5   Native American People Killed by Police (1/1/2013-12/31/2019)  12 non-null     float64
 6   Asian People Killed by Police (1/1/2013-12/31/2019)            33 non-null     float64
 7   Pacific Islanders Killed by Police (1/1/2013-12/31/2019)       9 non-null      float64
 8   White People Killed by Police (1/1/2013-12/31/2019)            91 non-null     float64
 9   Unknown Race People Killed by Police (1/1/2013-12/31/2019)     50 non-null     float64
 10  All People Killed by Police (1/1/2013-12/31/2019)              102 non-null    float64
 11  Total                                                          102 non-null    object
 12  Black                                                          102 non-null    object
 13  White                                                          102 non-null    object
 14  Amer. Indian                                                   101 non-null    object
 15  Asian                                                          101 non-null    object
 16  Hawaiian                                                       101 non-null    object
 17  Asian/Pacific Islander                                         101 non-null    object
 18  Other                                                          100 non-null    object
 19  Two or
more races                                              101 non-null    object
 20  Hispanic                                                       102 non-null    object
 21  Black-White Dissimilarity Index (2010)                         100 non-null    float64
 22  Murder and
nonnegligent manslaughter                           101 non-null    object
 23  Murder Rate                                                    102 non-null    float64
 24  Avg Annual Police Homicide Rate                                102 non-null    float64
 25  Avg Annual Police Homicide Rate for Black People               102 non-null    float64
 26  Avg Annual Police Homicide Rate for White People               102 non-null    float64
 27  Avg Annual Police Homicide Rate for Hispanic People            102 non-null    float64
 28  Black-White Disparity                                          102 non-null    object
 29  Hispanic-White Disparity                                       102 non-null    object
 30  Violent crimes 2013 (if reported by agency)                    99 non-null     float64
 31  Violent crimes 2014 (if reported by agency)                    96 non-null     float64
 32  Violent crimes 2015 (if reported by agency)                    97 non-null     float64
 33  Violent crimes 2016 (if reported by agency)                    95 non-null     float64
 34  Violent crimes 2017 (if reported by agency)                    92 non-null     float64
 35  Violent crimes 2018 (if reported by agency)                    97 non-null     float64
 36  Average Violent Crimes Reported (2013-17)                      101 non-null    float64
 37  Violent Crime Rate                                             101 non-null    float64
 38  2013 Total Arrests (UCR Data)                                  90 non-null     float64
 39  2014 Total Arrests                                             92 non-null     float64
 40  2015 Total Arrests                                             89 non-null     float64
 41  2016 Total Arrests                                             92 non-null     float64
 42  2017 Total Arrests                                             93 non-null     float64
 43  2018 Total Arrests                                             95 non-null     float64
 44  Estimated Average Arrests per Year                             100 non-null    object
 45  Killings by Police per 10k Arrests                             97 non-null     float64
dtypes: float64(29), object(17)
memory usage: 361.7+ KB

In [13]:
col_list = df_police_killings.columns

In [14]:
col_list

Index(['State', 'City', 'PD',
       'Black People Killed by Police (1/1/2013-12/31/2019)',
       'Hispanic People Killed by Police (1/1/2013-12/31/2019)',
       'Native American People Killed by Police (1/1/2013-12/31/2019)',
       'Asian People Killed by Police (1/1/2013-12/31/2019)',
       'Pacific Islanders Killed by Police (1/1/2013-12/31/2019)',
       'White People Killed by Police (1/1/2013-12/31/2019)',
       'Unknown Race People Killed by Police (1/1/2013-12/31/2019)',
       'All People Killed by Police (1/1/2013-12/31/2019)', 'Total', 'Black',
       'White', 'Amer. Indian', 'Asian', 'Hawaiian', 'Asian/Pacific Islander',
       'Other', 'Two or\nmore races', 'Hispanic',
       'Black-White Dissimilarity Index (2010)',
       'Murder and\nnonnegligent manslaughter', 'Murder Rate',
       'Avg Annual Police Homicide Rate',
       'Avg Annual Police Homicide Rate for Black People',
       'Avg Annual Police Homicide Rate for White People',
       'Avg Annual Police Homicide Rate for Hispanic People',
       'Black-White Disparity', 'Hispanic-White Disparity',
       'Violent crimes 2013 (if reported by agency)',
       'Violent crimes 2014 (if reported by agency)',
       'Violent crimes 2015 (if reported by agency)',
       'Violent crimes 2016 (if reported by agency)',
       'Violent crimes 2017 (if reported by agency)',
       'Violent crimes 2018 (if reported by agency)',
       'Average Violent Crimes Reported (2013-17)', 'Violent Crime Rate',
       '2013 Total Arrests (UCR Data)', '2014 Total Arrests',
       '2015 Total Arrests', '2016 Total Arrests', '2017 Total Arrests',
       '2018 Total Arrests', 'Estimated Average Arrests per Year',
       'Killings by Police per 10k Arrests'],
      dtype='object')

In [7]:
df_police_killings = df_police_killings[col_list]

In [15]:
df_police_killings.head()

,State,City,PD,Black People Killed by Police (1/1/2013-12/31/2019),Hispanic People Killed by Police (1/1/2013-12/31/2019),Native American People Killed by Police (1/1/2013-12/31/2019),Asian People Killed by Police (1/1/2013-12/31/2019),Pacific Islanders Killed by Police (1/1/2013-12/31/2019),White People Killed by Police (1/1/2013-12/31/2019),Unknown Race People Killed by Police (1/1/2013-12/31/2019),...,Average Violent Crimes Reported (2013-17),Violent Crime Rate,2013 Total Arrests (UCR Data),2014 Total Arrests,2015 Total Arrests,2016 Total Arrests,2017 Total Arrests,2018 Total Arrests,Estimated Average Arrests per Year,Killings by Police per 10k Arrests
0,New Mexico,Albuquerque,Albuquerque Police Department,3.0,18.0,NaN,NaN,NaN,11.0,NaN,...,6040.3,11.1,27700.0,25447.0,22126.0,20341.0,21130.0,22254.0,22259.6,14.4
1,California,Anaheim,Anaheim Police Department,3.0,7.0,NaN,NaN,NaN,3.0,NaN,...,1192.7,3.5,7891.0,8137.0,8381.0,9415.0,8869.0,10019.0,8964.2,14.5
2,Alaska,Anchorage,Anchorage Police Department,1.0,1.0,2.0,NaN,NaN,5.0,4.0,...,3179.3,10.9,17601.0,14748.0,14387.0,13294.0,13871.0,13973.0,14054.6,9.2
3,Texas,Arlington,Arlington Police Department,7.0,1.0,NaN,2.0,NaN,3.0,NaN,...,1921.8,5.3,17258.0,16222.0,13989.0,11024.0,8397.0,9566.0,11839.6,11.0
4,Georgia,Atlanta,Atlanta Police Department,13.0,NaN,NaN,NaN,NaN,1.0,1.0,...,4956.0,11.8,30505.0,26958.0,NaN,22161.0,22581.0,NaN,23900,6.3

In [19]:
col_list_2 = df_police_killings.columns.to_list()

In [20]:
col_list_2

["Victim's name",
 "Victim's age",
 "Victim's gender",
 "Victim's race",
 'URL of image of victim',
 'Date of Incident (month/day/year)',
 'Street Address of Incident',
 'City',
 'State',
 'Zipcode',
 'County',
 'Agency responsible for death',
 'ORI Agency Identifier (if available)',
 'Cause of death',
 'A brief description of the circumstances surrounding the death',
 'Official disposition of death (justified or other)',
 'Criminal Charges?',
 'Link to news article or photo of official document',
 'Symptoms of mental illness?',
 'Unarmed/Did Not Have an Actual Weapon',
 'Alleged Weapon (Source: WaPo and Review of Cases Not Included in WaPo Database)',
 'Alleged Threat Level (Source: WaPo)',
 'Fleeing (Source: WaPo)',
 'Body Camera (Source: WaPo)',
 'WaPo ID (If included in WaPo database)',
 'Off-Duty Killing?',
 'Geography (via Trulia methodology based on zipcode population density: http://jedkolko.com/wp-content/uploads/2015/05/full-ZCTA-urban-suburban-rural-classification.xlsx )',
 'MPV ID',
 'Fatal Encounters ID']

In [26]:
col_list_3 = ['victim_name', 'victim_age', 'victim_gender', 'victim_race', 'image_url', 'date_incident', 
              'address_incident', 'city', 'state', 'zipcode', 'county', 'agency', 'ori', 'cause_of_death', 
              'description', 'justified', 'criminal_charges', 'link', 'mental_illness', 'unarmed', 'alleged_weapon', 
              'threat_level', 'fleeing', 'body_camera', 'wapo_id', 'off_duty', 'geography', 'mpv_id', 'fe_id']

In [27]:
df_police_killings.columns = col_list_3

In [28]:
df_police_killings.head()

,victim_name,victim_age,victim_gender,victim_race,image_url,date_incident,address_incident,city,state,zipcode,...,unarmed,alleged_weapon,threat_level,fleeing,body_camera,wapo_id,off_duty,geography,mpv_id,fe_id
0,Name withheld by police,Unknown,Male,Unknown race,NaN,06/09/2020,337 Garrison Place,Virginia Beach,VA,23452.0,...,Allegedly Armed,knife,attack,Not fleeing,NaN,NaN,NaN,NaN,8448,28737.0
1,Name withheld by police,Unknown,Male,Unknown race,NaN,05/09/2020,4900 South Lavergne Avenue,Chicago,IL,60638.0,...,Allegedly Armed,knife,attack,Not fleeing,NaN,NaN,NaN,NaN,8446,28734.0
2,Name withheld by police,61,Male,Unknown race,NaN,05/09/2020,2118 Fredericksburg Rd,San Antonio,TX,78201.0,...,Allegedly Armed,knife,attack,Not fleeing,NaN,NaN,off-duty,NaN,8447,28735.0
3,Name withheld by police,22,Male,Unknown race,NaN,05/09/2020,2500 Logistics Drive,Battle Creek,MI,49037.0,...,Vehicle,vehicle,attack,Car,NaN,NaN,NaN,NaN,8449,28736.0
4,Steven D. Smith,33,Male,Unknown race,NaN,04/09/2020,200 N. State Street,Syracuse,NY,13203.0,...,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,NaN,8444,28726.0

In [29]:
df_police_killings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8427 entries, 0 to 8426
Data columns (total 29 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   victim_name       8427 non-null   object
 1   victim_age        8427 non-null   object
 2   victim_gender     8415 non-null   object
 3   victim_race       8427 non-null   object
 4   image_url         4539 non-null   object
 5   date_incident     8427 non-null   object
 6   address_incident  8340 non-null   object
 7   city              8421 non-null   object
 8   state             8427 non-null   object
 9   zipcode           8391 non-null   float64
 10  county            8413 non-null   object
 11  agency            8412 non-null   object
 12  ori               8426 non-null   object
 13  cause_of_death    8427 non-null   object
 14  description       8410 non-null   object
 15  justified         8416 non-null   object
 16  criminal_charges  8427 non-null   object
 17  link              8416 non-null   object
 18  mental_illness    8418 non-null   object
 19  unarmed           8427 non-null   object
 20  alleged_weapon    8427 non-null   object
 21  threat_level      5980 non-null   object
 22  fleeing           5546 non-null   object
 23  body_camera       5433 non-null   object
 24  wapo_id           5515 non-null   float64
 25  off_duty          239 non-null    object
 26  geography         8411 non-null   object
 27  mpv_id            8427 non-null   int64
 28  fe_id             8345 non-null   float64
dtypes: float64(3), int64(1), object(25)
memory usage: 1.9+ MB

In [32]:
df_police_killings['mpv_id'].value_counts()

8449    2
5972    2
2047    1
7489    1
7465    1
       ..
645     1
6790    1
4743    1
2700    1
2049    1
Name: mpv_id, Length: 8425, dtype: int64

In [33]:
mpv_8449 = df_police_killings[df_police_killings['mpv_id']==8449]

In [34]:
mpv_8449

,victim_name,victim_age,victim_gender,victim_race,image_url,date_incident,address_incident,city,state,zipcode,...,unarmed,alleged_weapon,threat_level,fleeing,body_camera,wapo_id,off_duty,geography,mpv_id,fe_id
3,Name withheld by police,22,Male,Unknown race,NaN,05/09/2020,2500 Logistics Drive,Battle Creek,MI,49037.0,...,Vehicle,vehicle,attack,Car,NaN,NaN,NaN,NaN,8449,28736.0
2180,Fernando Cruz,18,Male,Hispanic,NaN,19/09/2018,3864 Whittier Boulevard,Los Angeles,CA,90023.0,...,Unarmed/Did Not Have an Actual Weapon,no object,NaN,NaN,NaN,NaN,NaN,Urban,8449,NaN

In [35]:
mpv_5972 = df_police_killings[df_police_killings['mpv_id']==5972]

In [36]:
mpv_5972

,victim_name,victim_age,victim_gender,victim_race,image_url,date_incident,address_incident,city,state,zipcode,...,unarmed,alleged_weapon,threat_level,fleeing,body_camera,wapo_id,off_duty,geography,mpv_id,fe_id
2473,Guillermo Perez,32,Male,Hispanic,NaN,16/06/2018,6425 Tyrone Ave,Van Nuys,CA,91401.0,...,Allegedly Armed,knife,attack,Not fleeing,No,3784.0,NaN,Urban,5972,24323.0
2474,Elizabeth Michele Tollison,49,Female,White,NaN,16/06/2018,6425 Tyrone Ave,Van Nuys,CA,91401.0,...,Unarmed/Did Not Have an Actual Weapon,no object,other,Not fleeing,No,3784.0,NaN,Urban,5972,24323.0

In [39]:
df_police_killings = df_police_killings.drop([3, 2473])

In [40]:
df_police_killings['mpv_id'].value_counts()

2047    1
3363    1
7465    1
1322    1
3371    1
       ..
645     1
6790    1
4743    1
2700    1
2049    1
Name: mpv_id, Length: 8425, dtype: int64

In [41]:
df_police_killings = df_police_killings.set_index('mpv_id')

In [42]:
df_police_killings.head()

,victim_name,victim_age,victim_gender,victim_race,image_url,date_incident,address_incident,city,state,zipcode,...,mental_illness,unarmed,alleged_weapon,threat_level,fleeing,body_camera,wapo_id,off_duty,geography,fe_id
mpv_id,,,,,,,,,,,,,,,,,,,,,
8448,Name withheld by police,Unknown,Male,Unknown race,NaN,06/09/2020,337 Garrison Place,Virginia Beach,VA,23452.0,...,No,Allegedly Armed,knife,attack,Not fleeing,NaN,NaN,NaN,NaN,28737.0
8446,Name withheld by police,Unknown,Male,Unknown race,NaN,05/09/2020,4900 South Lavergne Avenue,Chicago,IL,60638.0,...,No,Allegedly Armed,knife,attack,Not fleeing,NaN,NaN,NaN,NaN,28734.0
8447,Name withheld by police,61,Male,Unknown race,NaN,05/09/2020,2118 Fredericksburg Rd,San Antonio,TX,78201.0,...,No,Allegedly Armed,knife,attack,Not fleeing,NaN,NaN,off-duty,NaN,28735.0
8444,Steven D. Smith,33,Male,Unknown race,NaN,04/09/2020,200 N. State Street,Syracuse,NY,13203.0,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,NaN,28726.0
8445,Joshua Beedie,38,Male,White,https://fatalencounters.org/wp-content/uploads...,04/09/2020,38338 Old Woman Springs Rd,Lucerne Valley,CA,92356.0,...,No,Allegedly Armed,gun,attack,NaN,NaN,NaN,NaN,NaN,28732.0

In [43]:
df_police_killings = df_police_killings.sort_index()

In [44]:
df_police_killings.head()

,victim_name,victim_age,victim_gender,victim_race,image_url,date_incident,address_incident,city,state,zipcode,...,mental_illness,unarmed,alleged_weapon,threat_level,fleeing,body_camera,wapo_id,off_duty,geography,fe_id
mpv_id,,,,,,,,,,,,,,,,,,,,,
1,Mark Chavez,49,Male,Hispanic,http://www.tricitytribuneusa.com/wp-content/up...,01/01/2013,912 Loma Linda Ave.,Farmington,NM,87401.0,...,No,Allegedly Armed,blunt weapon,NaN,NaN,NaN,NaN,NaN,Urban,12175.0
2,Tyree Bell,31,Male,Black,http://content.omaha.com/media/maps/ps/2013/ja...,01/01/2013,3727 N. 42nd St.,Omaha,NE,68111.0,...,Yes,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Urban,12173.0
3,Abel Gurrola,26,Male,Hispanic,http://www.bakersfieldnow.com/news/local/A-26-...,01/01/2013,720 Terrace Way,Bakersfield,CA,93304.0,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Urban,12174.0
4,Christopher Tavares,21,Male,Hispanic,http://www.krdo.com/image/view/-/17980228/medR...,01/01/2013,Highway 50 and North Elizabeth Street,Pueblo,CO,81008.0,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Suburban,12176.0
5,Andrew L. Closson,21,Male,White,http://www.superiortelegram.com/sites/default/...,01/01/2013,U.S. Highway 53,Gordon,WI,54838.0,...,Drug or alcohol use,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Rural,12172.0

In [45]:
df_police_killings.columns

Index(['victim_name', 'victim_age', 'victim_gender', 'victim_race',
       'image_url', 'date_incident', 'address_incident', 'city', 'state',
       'zipcode', 'county', 'agency', 'ori', 'cause_of_death', 'description',
       'justified', 'criminal_charges', 'link', 'mental_illness', 'unarmed',
       'alleged_weapon', 'threat_level', 'fleeing', 'body_camera', 'wapo_id',
       'off_duty', 'geography', 'fe_id'],
      dtype='object')

In [62]:
df_police_killings['fe_id'].value_counts()

25885.0    1
23826.0    1
16553.0    1
16260.0    1
15914.0    1
          ..
28410.0    1
14239.0    1
28011.0    1
27959.0    1
12800.0    1
Name: fe_id, Length: 8343, dtype: int64

In [63]:
cols_to_remove = ['victim_name', 'image_url', 'address_incident', 'ori', 'description', 'link']

In [65]:
df_police_killings = df_police_killings.drop(cols_to_remove, axis=1)

In [66]:
df_police_killings.head()

,victim_age,victim_gender,victim_race,date_incident,city,state,zipcode,county,agency,cause_of_death,...,mental_illness,unarmed,alleged_weapon,threat_level,fleeing,body_camera,wapo_id,off_duty,geography,fe_id
mpv_id,,,,,,,,,,,,,,,,,,,,,
1,49,Male,Hispanic,01/01/2013,Farmington,NM,87401.0,San Juan,Farmington Police Department,Gunshot,...,No,Allegedly Armed,blunt weapon,NaN,NaN,NaN,NaN,NaN,Urban,12175.0
2,31,Male,Black,01/01/2013,Omaha,NE,68111.0,Douglas,Omaha Police Department,Gunshot,...,Yes,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Urban,12173.0
3,26,Male,Hispanic,01/01/2013,Bakersfield,CA,93304.0,Kern,Bakersfield Police Department,Gunshot,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Urban,12174.0
4,21,Male,Hispanic,01/01/2013,Pueblo,CO,81008.0,Pueblo,Pueblo Police Department,Gunshot,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Suburban,12176.0
5,21,Male,White,01/01/2013,Gordon,WI,54838.0,Douglas,Douglas County Sheriff's Office,Gunshot,...,Drug or alcohol use,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Rural,12172.0

In [67]:
df_police_killings['victim_race'].value_counts()

White               3711
Black               2121
Hispanic            1455
Unknown race         844
Asian                130
Native American      118
Pacific Islander      46
Name: victim_race, dtype: int64

In [68]:
df_police_killings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8425 entries, 1 to 8452
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   victim_age        8425 non-null   object
 1   victim_gender     8413 non-null   object
 2   victim_race       8425 non-null   object
 3   date_incident     8425 non-null   object
 4   city              8419 non-null   object
 5   state             8425 non-null   object
 6   zipcode           8389 non-null   float64
 7   county            8411 non-null   object
 8   agency            8410 non-null   object
 9   cause_of_death    8425 non-null   object
 10  justified         8414 non-null   object
 11  criminal_charges  8425 non-null   object
 12  mental_illness    8416 non-null   object
 13  unarmed           8425 non-null   object
 14  alleged_weapon    8425 non-null   object
 15  threat_level      5978 non-null   object
 16  fleeing           5544 non-null   object
 17  body_camera       5432 non-null   object
 18  wapo_id           5514 non-null   float64
 19  off_duty          239 non-null    object
 20  geography         8410 non-null   object
 21  fe_id             8343 non-null   float64
dtypes: float64(3), object(19)
memory usage: 1.5+ MB

In [69]:
#df['Date']= pd.to_datetime(df['Date'])
df_police_killings['date_incident'] = pd.to_datetime(df_police_killings['date_incident'])

In [70]:
df_police_killings.head()

,victim_age,victim_gender,victim_race,date_incident,city,state,zipcode,county,agency,cause_of_death,...,mental_illness,unarmed,alleged_weapon,threat_level,fleeing,body_camera,wapo_id,off_duty,geography,fe_id
mpv_id,,,,,,,,,,,,,,,,,,,,,
1,49,Male,Hispanic,2013-01-01,Farmington,NM,87401.0,San Juan,Farmington Police Department,Gunshot,...,No,Allegedly Armed,blunt weapon,NaN,NaN,NaN,NaN,NaN,Urban,12175.0
2,31,Male,Black,2013-01-01,Omaha,NE,68111.0,Douglas,Omaha Police Department,Gunshot,...,Yes,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Urban,12173.0
3,26,Male,Hispanic,2013-01-01,Bakersfield,CA,93304.0,Kern,Bakersfield Police Department,Gunshot,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Urban,12174.0
4,21,Male,Hispanic,2013-01-01,Pueblo,CO,81008.0,Pueblo,Pueblo Police Department,Gunshot,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Suburban,12176.0
5,21,Male,White,2013-01-01,Gordon,WI,54838.0,Douglas,Douglas County Sheriff's Office,Gunshot,...,Drug or alcohol use,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Rural,12172.0